//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBHANDLER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntryCV
    {
        public int CvID { get; set; }
        public string objective { get; set; }
        public string experience { get; set; }
        public int fscm { get; set; }
        public int matm { get; set; }
        public string skills { get; set; }
        public string acheivement { get; set; }
        public string projects { get; set; }
        public string intrest { get; set; }
        public string image { get; set; }
        public string hobby { get; set; }
        public string phoneno { get; set; }
        public System.DateTime dob { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    }
}
